services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      OLLAMA_INTEL_GPU: "false"
      OLLAMA_ALLOW_CPU: "true"
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  backend:
    build: .
    container_name: backend
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    volumes:
      - ./docs:/app/docs
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    restart: unless-stopped
    environment:
      GOOGLE_API_KEY: "AIzaSyASjRPSrBbtJLKMGrjDTSettxAvlTzcGB0"

  frontend:
    build: .
    container_name: frontend
    command: streamlit run frontend.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  ollama_data:
